services:
  apache:
    build: ./apache
    container_name: apache_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/conf:/etc/apache2/sites-enabled
      - certs:/etc/letsencrypt
    depends_on:
      - app

  app:
    build: ./
    container_name: next_app
    environment:
      NODE_ENV: production
    restart: always

volumes:
  certs:
